[package]
name = "emulator"
version = "0.1.0"
authors = ["Tomer Ayal <tomer.trc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust80286"

[[bin]]
name = "dos-emu"
path = "src/main.rs"

[dependencies]
