[package]
name = "xtreme86"
version = "0.1.0"
authors = ["Tomer Ayal <tomer.trc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "xtreme86"

[dependencies]
enumflags2 = "0.7.1"
dyn-clone = "1.0.4"
